-- Deterministic cleanup overrides for high-impact NY Medicaid CDT rules.
-- Run after:
--   006_nys_medicaid_cdt_rules.sql
--   007_nys_medicaid_cdt_rules_structured.sql

create schema if not exists coding_agent;

with src as (
  select id
  from coding_agent.rule_sources
  where source_slug = 'nys_medicaid_dental_2026'
)
insert into coding_agent.cdt_payer_rules_structured (
  code,
  payer_name,
  rule_type,
  rule_text,
  fee,
  age_min,
  age_max,
  frequency_count,
  frequency_period_months,
  requires_prior_auth,
  requires_report,
  allowed_pos_codes,
  restriction_exception_codes,
  not_billable_with_codes,
  section_label,
  source_page,
  conditions,
  source_id
)
values
-- Fluoride
(
  'D1206',
  'New York State Medicaid',
  'frequency_limit',
  'Topical fluoride varnish reimbursable once per 3 months through age 20. For age 21+ only approvable with RE 81/95 or qualifying salivary-gland compromise.',
  30.30,
  null,
  20,
  1,
  3,
  false,
  false,
  null,
  '{81,95}'::text[],
  null,
  'II. PREVENTITIVE D1000-D1999',
  30,
  '{"override":"manual_high_impact","source_slug":"nys_medicaid_dental_2026"}'::jsonb,
  (select id from src)
),
(
  'D1208',
  'New York State Medicaid',
  'frequency_limit',
  'Topical fluoride (non-varnish) reimbursable once per 6 months for ages 6-20. For age 21+ only approvable with RE 81/95 or qualifying salivary-gland compromise.',
  14.14,
  6,
  20,
  1,
  6,
  false,
  false,
  null,
  '{81,95}'::text[],
  null,
  'II. PREVENTITIVE D1000-D1999',
  30,
  '{"override":"manual_high_impact","source_slug":"nys_medicaid_dental_2026"}'::jsonb,
  (select id from src)
),
(
  'D1351',
  'New York State Medicaid',
  'age_limit',
  'Sealant per tooth restricted to permanent first/second molars for members age 5-15 with qualifying unrestored occlusal surfaces. Reapplication at most once every 5 years.',
  35.35,
  5,
  15,
  1,
  60,
  false,
  false,
  null,
  null,
  null,
  'II. PREVENTITIVE D1000-D1999',
  30,
  '{"override":"manual_high_impact","source_slug":"nys_medicaid_dental_2026"}'::jsonb,
  (select id from src)
),
(
  'D1354',
  'New York State Medicaid',
  'frequency_limit',
  'Caries arresting medicament (SDF): covered up to 2 times per tooth in 12 months, up to 4 times per tooth lifetime.',
  15.15,
  null,
  null,
  2,
  12,
  false,
  false,
  null,
  null,
  null,
  'II. PREVENTITIVE D1000-D1999',
  30,
  '{"override":"manual_high_impact","lifetime_limit_per_tooth":4,"source_slug":"nys_medicaid_dental_2026"}'::jsonb,
  (select id from src)
),

-- Sedation/anesthesia interactions
(
  'D9230',
  'New York State Medicaid',
  'age_limit',
  'Nitrous oxide reimbursable through age 20 when clinically necessary with covered dental services. For age 21+ only with RE 81/95. Not billable with D9222/D9223/D9239/D9243; if billed with D9244/D9245/D9246, only one is reimbursed.',
  25.00,
  null,
  20,
  null,
  null,
  false,
  false,
  null,
  '{81,95}'::text[],
  '{D9222,D9223,D9239,D9243,D9244,D9245,D9246}'::text[],
  'XII. ADJUNCTIVE GENERAL SERVICES D9000-D9999',
  64,
  '{"override":"manual_high_impact","source_slug":"nys_medicaid_dental_2026"}'::jsonb,
  (select id from src)
),
(
  'D9244',
  'New York State Medicaid',
  'age_limit',
  'Minimal sedation enteral reimbursable through age 20 when clinically necessary with covered services. For age 21+ only with RE 81/95. Not billable with D9222/D9223/D9239/D9243; if billed with D9230/D9245/D9246, only one sedation code is reimbursed.',
  25.00,
  null,
  20,
  null,
  null,
  false,
  false,
  null,
  '{81,95}'::text[],
  '{D9222,D9223,D9239,D9243,D9230,D9245,D9246}'::text[],
  'XII. ADJUNCTIVE GENERAL SERVICES D9000-D9999',
  64,
  '{"override":"manual_high_impact","source_slug":"nys_medicaid_dental_2026"}'::jsonb,
  (select id from src)
),
(
  'D9245',
  'New York State Medicaid',
  'age_limit',
  'Moderate sedation enteral reimbursable through age 20 when clinically necessary with covered services. For age 21+ only with RE 81/95. Not billable with D9222/D9223/D9239/D9243; if billed with D9230/D9244/D9246, only one sedation code is reimbursed.',
  25.00,
  null,
  20,
  null,
  null,
  false,
  false,
  null,
  '{81,95}'::text[],
  '{D9222,D9223,D9239,D9243,D9230,D9244,D9246}'::text[],
  'XII. ADJUNCTIVE GENERAL SERVICES D9000-D9999',
  64,
  '{"override":"manual_high_impact","source_slug":"nys_medicaid_dental_2026"}'::jsonb,
  (select id from src)
),
(
  'D9246',
  'New York State Medicaid',
  'age_limit',
  'Moderate sedation non-IV parenteral reimbursable through age 20 when clinically necessary with covered services. For age 21+ only with RE 81/95. Not billable with D9222/D9223/D9239/D9243; if billed with D9230/D9244/D9245, only one sedation code is reimbursed.',
  25.00,
  null,
  20,
  null,
  null,
  false,
  false,
  null,
  '{81,95}'::text[],
  '{D9222,D9223,D9239,D9243,D9230,D9244,D9245}'::text[],
  'XII. ADJUNCTIVE GENERAL SERVICES D9000-D9999',
  65,
  '{"override":"manual_high_impact","source_slug":"nys_medicaid_dental_2026"}'::jsonb,
  (select id from src)
),

-- Visit-level controls
(
  'D9430',
  'New York State Medicaid',
  'frequency_limit',
  'Office visit for observation is stand-alone (cannot be billed with another procedure same date). Limited to 4 instances per year per member. Report required.',
  20.20,
  null,
  null,
  4,
  12,
  false,
  true,
  null,
  '{81,95}'::text[],
  null,
  'XII. ADJUNCTIVE GENERAL SERVICES D9000-D9999',
  66,
  '{"override":"manual_high_impact","standalone":true,"source_slug":"nys_medicaid_dental_2026"}'::jsonb,
  (select id from src)
),
(
  'D9440',
  'New York State Medicaid',
  'billing_exclusion',
  'After-hours office visit cannot be billed with an examination, observation, or consultation. Report required.',
  20.20,
  null,
  null,
  null,
  null,
  false,
  true,
  null,
  null,
  '{D9430,D9310,D0120,D0140,D0145,D0150,D0160}'::text[],
  'XII. ADJUNCTIVE GENERAL SERVICES D9000-D9999',
  66,
  '{"override":"manual_high_impact","source_slug":"nys_medicaid_dental_2026"}'::jsonb,
  (select id from src)
),

-- Teledentistry markers
(
  'D9995',
  'New York State Medicaid',
  'place_of_service',
  'Teledentistry synchronous encounter marker; report with associated clinical service lines. No reimbursement for D9995 itself.',
  0.00,
  null,
  null,
  null,
  null,
  false,
  false,
  '{02,10,11}'::text[],
  null,
  null,
  'XII. ADJUNCTIVE GENERAL SERVICES D9000-D9999',
  69,
  '{"override":"manual_high_impact","source_slug":"nys_medicaid_dental_2026"}'::jsonb,
  (select id from src)
),
(
  'D9996',
  'New York State Medicaid',
  'place_of_service',
  'Teledentistry asynchronous encounter marker; report with associated clinical service lines. No reimbursement for D9996 itself.',
  0.00,
  null,
  null,
  null,
  null,
  false,
  false,
  '{02,10,11}'::text[],
  null,
  null,
  'XII. ADJUNCTIVE GENERAL SERVICES D9000-D9999',
  69,
  '{"override":"manual_high_impact","source_slug":"nys_medicaid_dental_2026"}'::jsonb,
  (select id from src)
),
(
  'D9997',
  'New York State Medicaid',
  'billing_exclusion',
  'Dental case management for OPWDD/TBI populations only (RE 81/95). Not stand-alone and not billable with D9430 or deep sedation/general anesthesia services.',
  29.29,
  null,
  null,
  null,
  null,
  false,
  false,
  null,
  '{81,95}'::text[],
  '{D9430,D9222,D9223,D9224,D9225,D9239,D9243}'::text[],
  'XII. ADJUNCTIVE GENERAL SERVICES D9000-D9999',
  69,
  '{"override":"manual_high_impact","standalone":false,"source_slug":"nys_medicaid_dental_2026"}'::jsonb,
  (select id from src)
)
on conflict (code, payer_name) do update set
  rule_type = excluded.rule_type,
  rule_text = excluded.rule_text,
  fee = excluded.fee,
  age_min = excluded.age_min,
  age_max = excluded.age_max,
  frequency_count = excluded.frequency_count,
  frequency_period_months = excluded.frequency_period_months,
  requires_prior_auth = excluded.requires_prior_auth,
  requires_report = excluded.requires_report,
  allowed_pos_codes = excluded.allowed_pos_codes,
  restriction_exception_codes = excluded.restriction_exception_codes,
  not_billable_with_codes = excluded.not_billable_with_codes,
  section_label = excluded.section_label,
  source_page = excluded.source_page,
  conditions = excluded.conditions,
  source_id = excluded.source_id;

-- Conflict helper view for adjudication engines:
-- materializes "do not bill together" relationships row-wise.
create or replace view coding_agent.v_cdt_code_exclusions as
select
  r.payer_name,
  r.code as code_a,
  x.code as code_b
from coding_agent.cdt_payer_rules_structured r
cross join lateral unnest(coalesce(r.not_billable_with_codes, '{}'::text[])) as x(code);

grant select on coding_agent.v_cdt_code_exclusions to service_role, authenticated, anon;
