"""Backward-compatible facade — re-exports reference and PHI database helpers."""

from __future__ import annotations

from app.eligibility.db_phi import (
    complete_eligibility_request_after_voice,
    complete_eligibility_request_processing,
    fail_eligibility_request_exhausted,
    fail_eligibility_request_processing,
    fetch_eligibility_request_row,
    fetch_retryable_requests,
    get_eligibility_agent_settings,
    get_eligibility_check_by_id,
    get_latest_eligibility_check,
    get_latest_eligibility_for_patient,
    insert_audit_log,
    insert_eligibility_check,
    insert_eligibility_request_event,
    insert_procedure_estimates,
    list_audit_for_patient,
    list_procedure_estimates,
    lock_eligibility_request_for_processing,
    merge_eligibility_request_output_json,
    requeue_eligibility_request,
    touch_eligibility_agent_settings_sync,
    update_eligibility_check_fields,
)
from app.eligibility.db_reference import (
    decimal_or_none,
    fetch_active_provider_payer_network,
    fetch_existing_cdt_codes,
    fetch_payer_fee_schedule_as_dict,
    get_supabase,
    payer_requires_prior_auth,
    reset_supabase_client,
    validate_dental_payer,
)

__all__ = [
    "complete_eligibility_request_after_voice",
    "complete_eligibility_request_processing",
    "decimal_or_none",
    "fail_eligibility_request_exhausted",
    "fail_eligibility_request_processing",
    "fetch_active_provider_payer_network",
    "fetch_eligibility_request_row",
    "fetch_existing_cdt_codes",
    "fetch_payer_fee_schedule_as_dict",
    "fetch_retryable_requests",
    "get_eligibility_agent_settings",
    "get_eligibility_check_by_id",
    "get_latest_eligibility_check",
    "get_latest_eligibility_for_patient",
    "get_supabase",
    "insert_audit_log",
    "insert_eligibility_check",
    "insert_eligibility_request_event",
    "insert_procedure_estimates",
    "list_audit_for_patient",
    "list_procedure_estimates",
    "lock_eligibility_request_for_processing",
    "merge_eligibility_request_output_json",
    "payer_requires_prior_auth",
    "requeue_eligibility_request",
    "reset_supabase_client",
    "touch_eligibility_agent_settings_sync",
    "update_eligibility_check_fields",
    "validate_dental_payer",
]
